export interface WeChatThemeOptions {
  themeColor: string;
  fontSize: number;
  lineHeight: number;
}

export const getWeChatStyles = ({
  themeColor,
  fontSize,
  lineHeight,
}: WeChatThemeOptions) => {
  const baseStyle = {
    fontSize: `${fontSize}px`,
    lineHeight: lineHeight,
    color: '#3e3e3e',
    fontFamily:
      'Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, "PingFang SC", Cambria, Cochin, Georgia, Times, "Times New Roman", serif',
    letterSpacing: '0.05em',
    wordWrap: 'break-word' as const,
  };

  return {
    wrapper: {
      ...baseStyle,
      padding: '16px',
    },
    h1: {
      fontSize: '1.6em',
      color: themeColor,
      fontWeight: 'bold',
      textAlign: 'center' as const,
      marginTop: '1.5em',
      marginBottom: '1em',
      lineHeight: 1.4,
    },
    h2: {
      fontSize: '1.4em',
      color: themeColor,
      fontWeight: 'bold',
      marginTop: '1.5em',
      marginBottom: '1em',
      borderBottom: `2px solid ${themeColor}`,
      paddingBottom: '0.2em',
      lineHeight: 1.4,
    },
    h3: {
      fontSize: '1.2em',
      color: themeColor,
      fontWeight: 'bold',
      marginTop: '1.2em',
      marginBottom: '0.8em',
      lineHeight: 1.4,
    },
    p: {
      margin: '0 0 1.5em 0',
      textAlign: 'justify' as const,
    },
    blockquote: {
      borderLeft: `4px solid ${themeColor}`,
      padding: '10px 15px',
      color: '#777',
      backgroundColor: '#f8f8f8',
      margin: '1em 0',
      borderRadius: '4px',
      fontSize: '0.95em',
    },
    ul: {
      marginTop: '0.8em',
      marginBottom: '0.8em',
      paddingLeft: '2em',
      listStyleType: 'disc',
    },
    ol: {
      marginTop: '0.8em',
      marginBottom: '0.8em',
      paddingLeft: '2em',
      listStyleType: 'decimal',
    },
    li: {
      marginBottom: '0.5em',
    },
    a: {
      color: themeColor,
      textDecoration: 'none',
      borderBottom: `1px solid ${themeColor}`,
    },
    strong: {
      color: themeColor,
      fontWeight: 'bold',
    },
    em: {
      fontStyle: 'italic',
      color: themeColor,
    },
    code: {
      backgroundColor: '#f8f8f8',
      padding: '2px 4px',
      borderRadius: '4px',
      color: '#e96900',
      fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
      fontSize: '0.9em',
      wordBreak: 'break-all' as const,
    },
    codeWrapper: {
      backgroundColor: '#282c34',
      borderRadius: '8px',
      marginTop: '1.5em',
      marginBottom: '1.5em',
      marginLeft: '0',
      marginRight: '0',
      overflow: 'hidden',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    },
    codeHeaderTable: {
      width: '100%',
      backgroundColor: '#21252b',
      borderCollapse: 'collapse' as const,
      borderSpacing: '0',
      margin: '0',
      padding: '0',
      border: 'none',
    },
    codeDotsTd: {
      paddingTop: '12px',
      paddingBottom: '12px',
      paddingLeft: '16px',
      paddingRight: '0',
      textAlign: 'left' as const,
      verticalAlign: 'middle',
      border: 'none',
    },
    codeLangTd: {
      paddingTop: '12px',
      paddingBottom: '12px',
      paddingLeft: '0',
      paddingRight: '16px',
      textAlign: 'right' as const,
      verticalAlign: 'middle',
      color: '#abb2bf',
      fontSize: '12px',
      fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
      textTransform: 'uppercase' as const,
      fontWeight: 'bold',
      letterSpacing: '0.05em',
      lineHeight: '12px',
      border: 'none',
    },
    codeDot: {
      display: 'inline-block',
      width: '12px',
      height: '12px',
      borderRadius: '50%',
      marginRight: '8px',
      verticalAlign: 'middle',
      fontSize: '0px',
      lineHeight: '0px',
    },
    codeDotRed: { backgroundColor: '#ff5f56' },
    codeDotYellow: { backgroundColor: '#ffbd2e' },
    codeDotGreen: { backgroundColor: '#27c93f' },
    pre: {
      backgroundColor: '#282c34',
      color: '#abb2bf',
      paddingTop: '16px',
      paddingRight: '16px',
      paddingBottom: '16px',
      paddingLeft: '16px',
      marginTop: '0',
      marginBottom: '0',
      marginLeft: '0',
      marginRight: '0',
      overflowX: 'auto' as const,
      fontFamily: 'Menlo, Monaco, Consolas, "Courier New", monospace',
      fontSize: '0.9em',
      lineHeight: 1.5,
      whiteSpace: 'pre' as const,
      wordWrap: 'normal' as const,
      wordBreak: 'normal' as const,
    },
    img: {
      maxWidth: '100%',
      height: 'auto',
      display: 'block',
      margin: '1em auto',
      borderRadius: '8px',
    },
    hr: {
      border: 'none',
      borderTop: '1px solid #eee',
      margin: '2em 0',
    },
    table: {
      width: '100%',
      borderCollapse: 'collapse' as const,
      marginBottom: '1.5em',
      fontSize: '0.9em',
    },
    th: {
      border: '1px solid #dfdfdf',
      padding: '8px',
      backgroundColor: '#f8f8f8',
      fontWeight: 'bold',
      color: themeColor,
    },
    td: {
      border: '1px solid #dfdfdf',
      padding: '8px',
    },
  };
};
